### ISSUE TITLE
Is it possible to port this to BetterDiscord?

### ISSUE THREAD

**Issue by brian6932** [vizality-community/channel-members-activity-icons#1]
Should be possible

**Comment by resucutie** [comment]
Yes, it is, but it will require a complete rewrite of the source code due to how Vizality plugins works

**Comment by brian6932** [comment]
Ah no rush then. Is it possible to run both Vizality and BetterDiscord simultaneously, or do the client mods mess with one another?

**Comment by WinstonSepruko** [comment]
You can run them both at once, however it is not recommended and also requires a lot of fiddling just to get them both to inject.

**Comment by dperolio** [comment]
BD and Vizality are not meant to run together, but it is possible with effort and programming knowledge. I recommend simply choosing whichever you like the best, and if plugin(s) don't exist on the one you choose, request for them to be made.
